# ================= SETUP =================
[phases.setup]
nixPkgs = [
  "python311",
  "ffmpeg-full",
  "gcc",
  "libsodium"
]

# ================= INSTALL =================
[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt"
]

# ================= START =================
[start]
cmd = "apt-get update && apt-get install -y ffmpeg && which ffmpeg && python bot.py"
